name: 🚀 Feature Request
description: I have a suggestion 😻!
labels: [':sparkles: Feature Request']
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: What is the motivation / use case for changing the behavior?
      description: Describe the motivation or the concrete use case

  - type: textarea
    validations:
      required: true
    attributes:
      label: "Describe the solution you'd like"
      description: A clear and concise description of what you want to happen. Add any considered drawbacks
